### ISSUE TITLE
Fetch client docs

### ISSUE THREAD

**Issue by Vheissu** [aurelia/v1-documentation#38]
Documentation for working with the Fetch client package.

**Comment by bigopon** [comment]
It seems we are encouraging this doc
![Image](https://github.com/user-attachments/assets/6bb085e1-f943-49df-8c78-572d9f34541a)

Is this from current v1, it seems it should be more DI centric.

**Comment by Vheissu** [comment]
@bigopon This is what we were encouraging in the v1 docs, yeah. I am happy to recommend a more DI-centric approach if you think that's the way to go here. I'll actually add something to the top about how you can inject it and use the singleton pattern to ensure the same instance is used.
