### ISSUE TITLE
Notes on invoice 21/08/2024

### ISSUE THREAD

**Issue by Vheissu** [aurelia/v1-documentation#9]
OpenCollective doesn't allow comments on expenses to be public, so they are here for reference:

The expense: https://opencollective.com/aurelia/expenses/216777

This is a work in progress for porting over the Aurelia 1 documentation to Gitbook. Structural changes have been made as part of this work, and new content has been added and modernised.

With the work done in this batch, the introduction section, including the contact manager tutorial and Aurelia for new developers section, is completed. We also have two expandable sections in the templates for template syntax and basics, covering things like bindings and whatnot.

For reference, these are the GitHub issues created for this work:

https://github.com/aurelia/v1-documentation/issues/3
https://github.com/aurelia/v1-documentation/issues/5
https://github.com/aurelia/v1-documentation/issues/6
https://github.com/aurelia/v1-documentation/issues/7
https://github.com/aurelia/v1-documentation/issues/8

**Comment by bigopon** [comment]
Let's use the comment section in the expense to explain the work.
